#!/bin/bash

SOUND=0
wtime_audio="/home/kurush/downloads/audio/arcade.mp3"
ptime_audio="/home/kurush/downloads/audio/MetalSlug-MissionComplete.mp3"

#Check if audio is playable
check_audio(){
	`mpg123 -qt $ptime_audio 2>/dev/null`
	if [ $? -eq 1 ]; then
		echo "Error ptime_audio isn't a path to a playable sound file" && exit 3
	fi

	`mpg123 -qt $wtime_audio 2>/dev/null`
	if [ $? -eq 1 ]; then
		echo "Error ptime_audio isn't a path to a playable sound file" && exit 3
	fi
}


#Usage
usage(){
	echo """
Usage: $0 [OPTION] wtime ptime rep

Examples: 
25 minutes worktime, 5 minutes pausetime, 1 repetition, with sound
$0 -s 

50 minutes worktime, 10 minutes pause time, 2 repetitions, no sound:
$0 50 10 2 """
	exit 1
}

#Assign worktime, pausetime, repetitions 
wtime=25
ptime=5
rep=1
assign_variables(){
	[[ $1 == ?(-)+([0-9]) ]] && [ $1 -gt 0 ] && rep=$1
	[[ $2 == ?(-)+([0-9]) ]] && [ $2 -gt 0 ] && wtime=$2
	[[ $3 == ?(-)+([0-9]) ]] && [ $3 -gt 0 ] && ptime=$3
}

#Parsing input
optstring=":s:h"

while getopts ${optstring} arg; do
	case "${arg}" in
		s) 
			SOUND=1
			check_audio
			assign_variables $2 $3 $4 
			;;
		:) 
			assign_variables $1 $2 $3 
			;;
		h|?) 
			usage 
			exit 1
			;;
	esac
done

#Assigning variables
#wtime=25
#ptime=5
#rep=1

#[[ $1 == ?(-)+([0-9]) ]] && [ $1 -gt 0 ] && rep=$1
#[[ $2 == ?(-)+([0-9]) ]] && [ $2 -gt 0 ] && wtime=$2
#[[ $3 == ?(-)+([0-9]) ]] && [ $3 -gt 0 ] && ptime=$3

# Pomodoro
while [ $rep > 0 ]
do
	`sleep ${wtime}m`
	notify-send -t 5000 -i task-due "Pause Time" 
	[[ $SOUND -eq 1 ]] && `mpg123 -q $ptime_audio 2>/dev/null`

	`sleep ${ptime}m`
	((rep--))

	if [ rep != 0 ]; then
		notify-send -t 5000 -i task-due "Work Time" 
		[[ $SOUND -eq 1 ]] && `mpg123 -q $wtime_audio 2>/dev/null`
	fi
done

notify-send -t 5000 -i task-due "Your pomodoro session is over!" 
[[ $SOUND -eq 1 ]] && `mpg123 -q $ptime_audio 2>/dev/null`

exit 0
